import HeaderWrapper from "@/components/main-header/headerWrapper";
import Header from "@/components/main-header/main-header";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Research Lab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <HeaderWrapper>
          <Header />
          {children}
          <div id="modal-root"></div>
        </HeaderWrapper>
      </body>
    </html>
  );
}
